(() => {
  const cfg=window.AZU_CONFIG||{API_BASE:""};const API=String(cfg.API_BASE||"").replace(/\/$/,"");
  let session=sessionStorage.getItem("azuscripts_session")||"";let me=null;let cards=[];let selectedGradient="violet";
  const gradients={violet:["#7d68ff","#cf5dff"],cyan:["#34d9ff","#5376ff"],sunset:["#ff6b7a","#ff9c55"],rose:["#ff4fa8","#7c5cff"],toxic:["#7bff70","#12d7bd"],ice:["#ecf6ff","#5d8dff"],blueRed:["#2d77ff","#ff4b6e"]};
  const $=s=>document.querySelector(s);function toast(m){const t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),2400)}
  function api(path,options={}){const headers={Accept:"application/json",...(options.body?{"Content-Type":"application/json"}:{}),...(options.headers||{})};if(session)headers.Authorization=`Bearer ${session}`;return fetch(API+path,{...options,headers})}
  function status(el,msg,ok=false){el.textContent=msg;el.className="status "+(ok?"ok":"error")}
  function fillGradients(){const wrap=$("#gradientChoices");wrap.innerHTML="";Object.entries(gradients).forEach(([name,v])=>{const b=document.createElement("button");b.type="button";b.className="gradient-choice"+(name===selectedGradient?" active":"");b.title=name;b.style.background=`linear-gradient(135deg,${v[0]},${v[1]})`;b.onclick=()=>{selectedGradient=name;fillGradients();renderPreview()};wrap.appendChild(b)})}
  function renderPreview(){const c=$("#previewCard");const [a,b]=gradients[selectedGradient];c.style.background=`linear-gradient(145deg,rgba(255,255,255,.08),rgba(255,255,255,.025)),linear-gradient(135deg,${a}1a,${b}12)`;$("#previewTitle").textContent=$("#cardTitle").value||"Card title";$("#previewCategory").textContent=($("#cardCategory").value||"Other").toUpperCase();$("#previewVersion").textContent=$("#cardVersion").value||"V1.0";$("#previewDescription").textContent=$("#cardDescription").value||"Your description appears here.";const src=$("#cardImage").value.trim();$("#previewImage").src=src||"assets/anime-ability-arena.png";$("#previewTags").innerHTML="";$("#cardTags").value.split(",").map(x=>x.trim()).filter(Boolean).slice(0,4).forEach(t=>{const s=document.createElement("span");s.className="tag";s.textContent=t;$("#previewTags").appendChild(s)})}
  function resetForm(){$("#cardForm").reset();$("#cardId").value="";selectedGradient="violet";fillGradients();renderPreview();$("#editorTitle").textContent="Create a card";$("#deleteCardBtn").classList.add("hidden");$("#formStatus").textContent=""}
  function editCard(c){$("#cardId").value=c.id;$("#cardTitle").value=c.title||"";$("#cardGame").value=c.game||"";$("#cardVersion").value=c.version||"";$("#cardCategory").value=c.category||"Other";$("#cardDescription").value=c.description||"";$("#cardImage").value=c.image||"";$("#cardRedirect").value=c.redirect||"";$("#cardTags").value=Array.isArray(c.tags)?c.tags.join(", "):"";$("#cardAccent").value=/^#[0-9a-f]{6}$/i.test(c.accent||"")?c.accent:"#6b7cff";selectedGradient=gradients[c.gradient]?c.gradient:"violet";fillGradients();renderPreview();$("#editorTitle").textContent=`Edit: ${c.title}`;$("#deleteCardBtn").classList.remove("hidden");$("#editorPanel").scrollIntoView({behavior:"smooth",block:"start"})}
  function renderCards(){const wrap=$("#adminCards");wrap.innerHTML="";$("#adminResultCount").textContent=String(cards.length);$("#metricCards").textContent=String(cards.length);cards.forEach(c=>{const row=document.createElement("div");row.className="admin-card";const img=document.createElement("img");img.src=c.image||"";img.alt="";const info=document.createElement("div");const h=document.createElement("h3");h.textContent=c.title;const p=document.createElement("p");p.textContent=`${c.category||"Other"} · ${c.version||"V1"}`;const small=document.createElement("span");small.className="muted";small.textContent=c.id;info.append(h,p,small);const acts=document.createElement("div");acts.className="card-actions";const edit=document.createElement("button");edit.className="tiny-btn";edit.textContent="Edit";edit.onclick=()=>editCard(c);const del=document.createElement("button");del.className="tiny-btn";del.textContent="Delete";del.onclick=()=>deleteCard(c);acts.append(edit,del);row.append(img,info,acts);wrap.appendChild(row)});$("#adminEmpty").classList.toggle("hidden",cards.length>0)}
  async function loadMe(){const r=await api("/api/me");if(!r.ok){session="";sessionStorage.removeItem("azuscripts_session");throw new Error("Unauthorized")};me=await r.json();$("#sessionChip").textContent=`${me.id} · ${me.role}`;$("#welcomeTitle").textContent=`Welcome, ${me.id}`;$("#roleLine").textContent=`Role: ${me.role}. Your permissions are enforced by the API.`;$("#metricRole").textContent=me.role;$("#metricToday").textContent=me.dailyCreates<0?"Unlimited":`${me.dailyCreatesRemaining} / ${me.dailyCreates}`;$("#quotaText").textContent=me.dailyCreates<0?"Unlimited creations":`${me.dailyCreatesRemaining} creates left today`;if(me.role==="admin")$("#adminTools").classList.remove("hidden")}
  async function loadCards(){const r=await api("/api/me/cards");const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not load cards");cards=j.cards||[];renderCards();}
  async function login(e){e.preventDefault();const st=$("#loginStatus");status(st,"Authenticating…",true);const user=$("#loginUser").value.trim();const hwid=$("#loginHwid").value.trim();try{const r=await api("/api/auth/login",{method:"POST",body:JSON.stringify({userId:user,hwid})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Login failed");session=j.token;sessionStorage.setItem("azuscripts_session",session);await showConsole()}catch(err){status(st,err.message||"Login failed",false)}}
  async function showConsole(){try{await loadMe();await loadCards();$("#loginView").classList.add("hidden");$("#consoleView").classList.remove("hidden")}catch(e){$("#loginView").classList.remove("hidden");$("#consoleView").classList.add("hidden");status($("#loginStatus"),"This device/IP is not authorized.",false)}}
  async function saveCard(e){e.preventDefault();const body={title:$("#cardTitle").value.trim(),game:$("#cardGame").value.trim(),version:$("#cardVersion").value.trim(),category:$("#cardCategory").value,description:$("#cardDescription").value.trim(),image:$("#cardImage").value.trim(),redirect:$("#cardRedirect").value.trim(),tags:$("#cardTags").value.split(",").map(x=>x.trim()).filter(Boolean),accent:$("#cardAccent").value,gradient:selectedGradient};const id=$("#cardId").value;try{const r=await api(id?`/api/cards/${encodeURIComponent(id)}`:"/api/cards",{method:id?"PUT":"POST",body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||"Save failed");toast(id?"Card updated.":"Card created.");resetForm();await Promise.all([loadCards(),loadMe()])}catch(err){status($("#formStatus"),err.message||"Save failed")}}
  async function deleteCard(c){if(!confirm(`Delete “${c.title}”?`))return;try{const r=await api(`/api/cards/${encodeURIComponent(c.id)}`,{method:"DELETE"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Delete failed");toast("Card deleted.");if($("#cardId").value===c.id)resetForm();await Promise.all([loadCards(),loadMe()])}catch(err){toast(err.message||"Delete failed")}}
  async function authorize(e){e.preventDefault();try{const r=await api("/api/admin/devices",{method:"POST",body:JSON.stringify({userId:$("#deviceUser").value.trim(),role:$("#deviceRole").value,hwid:$("#deviceHwid").value.trim(),ip:$("#deviceIp").value.trim()})});const j=await r.json();if(!r.ok)throw new Error(j.error);status($("#deviceStatus"),"Device authorized.",true);e.target.reset();await loadUsers()}catch(err){status($("#deviceStatus"),err.message||"Could not authorize")}}
  async function loadUsers(){const r=await api("/api/admin/users");const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not load users");const w=$("#usersList");w.innerHTML="";(j.users||[]).forEach(u=>{const row=document.createElement("div");row.className="user-row";const left=document.createElement("span");left.textContent=`${u.id} · ${u.role}`;const right=document.createElement("span");right.textContent=`devices: ${u.devices} · cards: ${u.cards}`;row.append(left,right);w.appendChild(row)})}
  function logout(){session="";sessionStorage.removeItem("azuscripts_session");location.reload()}
  ["cardTitle","cardGame","cardVersion","cardDescription","cardImage","cardTags","cardCategory"].forEach(id=>$("#"+id).addEventListener("input",renderPreview));$("#cardAccent").addEventListener("input",renderPreview);$("#loginForm").addEventListener("submit",login);$("#cardForm").addEventListener("submit",saveCard);$("#newCardBtn").addEventListener("click",resetForm);$("#cancelEdit").addEventListener("click",resetForm);$("#deleteCardBtn").addEventListener("click",()=>{const c=cards.find(x=>x.id===$("#cardId").value);if(c)deleteCard(c)});$("#logoutBtn").addEventListener("click",logout);$("#getHwidCommand").addEventListener("click",async()=>{try{await navigator.clipboard.writeText('powershell -NoProfile -ExecutionPolicy Bypass -File .\\get-hwid.ps1');toast("HWID helper command copied.")}catch{toast("Clipboard blocked.")}});$("#deviceForm").addEventListener("submit",authorize);fillGradients();renderPreview();const preset=new URLSearchParams(location.search).get("card");showConsole().then(()=>{if(preset){const c=cards.find(x=>x.id===preset);if(c)editCard(c)}});
})();
