(() => {
  const cfg = window.AZU_CONFIG || { API_BASE: "" };
  const API = String(cfg.API_BASE || "").replace(/\/$/, "");
  const state = { cards: [], filtered: [], category: "All" };
  const gradients = { violet:["#7d68ff","#cf5dff"], cyan:["#34d9ff","#5376ff"], sunset:["#ff6b7a","#ff9c55"], rose:["#ff4fa8","#7c5cff"], toxic:["#7bff70","#12d7bd"], ice:["#ecf6ff","#5d8dff"], blueRed:["#2d77ff","#ff4b6e"] };
  const $ = s => document.querySelector(s); const $$ = (s,r=document) => [...r.querySelectorAll(s)]; const text = v => String(v ?? "");
  const icon = { arrow:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h13M13 6l6 6-6 6"/></svg>', copy:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="8" y="8" width="11" height="11" rx="2"/><path d="M15 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h2"/></svg>' };
  const api = (path, options={}) => fetch(API + path, { ...options, cache:"no-store", headers:{ Accept:"application/json", ...(options.body?{"Content-Type":"application/json"}:{}), ...(options.headers||{}) } });
  const safeImage = v => { const s=String(v||"").trim(); if(!s) return "assets/anime-ability-arena.png"; try { if(s.startsWith("https://")) return new URL(s).href; if(s.startsWith("/")||/^[A-Za-z0-9._-]+\//.test(s)) return new URL(s,location.href).href; } catch{} return "assets/anime-ability-arena.png"; };
  const safeExternal = v => { try { const u = new URL(v,location.href); return u.protocol === "https:" ? u.href : ""; } catch { return ""; } };
  const toast = m => { const e=$("#toast"); if(!e)return; e.textContent=m;e.classList.add("show");clearTimeout(window.__azToast);window.__azToast=setTimeout(()=>e.classList.remove("show"),2200); };

  function attachTilt(root=document){
    $$(".tilt-card:not([data-tilt-ready])",root).forEach(card=>{
      card.dataset.tiltReady="1"; let raf=0,rect,active=false,tx=0.5,ty=0.5; const strength=Number(card.dataset.tiltStrength||4.5);
      const draw=()=>{ raf=0; if(!active)return; const rx=(.5-ty)*strength,ry=(tx-.5)*strength; card.style.setProperty("--mx",`${(tx*100).toFixed(1)}%`);card.style.setProperty("--my",`${(ty*100).toFixed(1)}%`);card.style.transform=`perspective(1200px) rotateX(${rx.toFixed(2)}deg) rotateY(${ry.toFixed(2)}deg) translate3d(0,-5px,0) scale(1.012)`; };
      const schedule=()=>{if(!raf)raf=requestAnimationFrame(draw)};
      card.addEventListener("pointerenter",e=>{if(e.pointerType==="touch")return;active=true;rect=card.getBoundingClientRect();card.classList.add("is-hover");card.querySelector(".glass-sweep")?.classList.remove("sweep-now");void card.offsetWidth;card.querySelector(".glass-sweep")?.classList.add("sweep-now");card.style.transition="transform 90ms ease-out, box-shadow 220ms ease";tx=.5;ty=.5;schedule();});
      card.addEventListener("pointermove",e=>{if(!active||e.pointerType==="touch")return;rect ||= card.getBoundingClientRect();tx=Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width));ty=Math.max(0,Math.min(1,(e.clientY-rect.top)/rect.height));schedule();});
      card.addEventListener("pointerleave",e=>{if(e.pointerType==="touch")return;active=false;card.classList.remove("is-hover");card.style.transition="transform 440ms cubic-bezier(.2,.75,.2,1), box-shadow 260ms ease";card.style.transform="";card.style.setProperty("--mx","50%");card.style.setProperty("--my","50%");if(raf)cancelAnimationFrame(raf);raf=0;rect=null;});
    });
  }

  function renderFilters(){ const cats=["All",...new Set(state.cards.map(c=>text(c.category).trim()).filter(Boolean))];const wrap=$("#filters");wrap.replaceChildren();cats.forEach(cat=>{const b=document.createElement("button");b.type="button";b.className=`filter-chip${cat===state.category?" active":""}`;b.textContent=cat;b.addEventListener("click",()=>{state.category=cat;renderFilters();renderCards();});wrap.appendChild(b);}); }
  function cardElement(card,index){ const a=document.createElement("article");a.className="script-card tilt-card";a.dataset.tiltStrength="4.5";a.style.setProperty("--delay",`${Math.min(index*45,320)}ms`);a.style.setProperty("--accent",card.accent||"#6d7cff");a.style.setProperty("--accent-end",card.accentEnd||gradients[card.gradient]?.[1]||"#9a5eff");
    const media=document.createElement("div");media.className="card-media";const img=document.createElement("img");img.src=safeImage(card.image);img.alt=text(card.title);img.loading="lazy";img.referrerPolicy="no-referrer";const overlay=document.createElement("div");overlay.className="card-overlay";const sweep=document.createElement("div");sweep.className="glass-sweep";const meta=document.createElement("div");meta.className="media-meta";const status=document.createElement("span");status.className=`status-chip ${text(card.status||"Live").toLowerCase()}`;status.innerHTML=`<span class="status-dot"></span>${text(card.status||"Live")}`;const version=document.createElement("span");version.className="version-chip";version.textContent=text(card.version||"V1.0");meta.append(status,version);media.append(img,overlay,sweep,meta);
    const content=document.createElement("div");content.className="card-content";const context=document.createElement("div");context.className="card-context";const game=document.createElement("span");game.textContent=text(card.game||"Game");const dot=document.createElement("span");dot.className="context-dot";const category=document.createElement("span");category.className="category-chip";category.textContent=text(card.category||"Other");context.append(game,dot,category);const title=document.createElement("h3");title.textContent=text(card.title||"Untitled");const p=document.createElement("p");p.textContent=text(card.description||"");const tags=document.createElement("div");tags.className="tag-row";(Array.isArray(card.tags)?card.tags:[]).slice(0,4).forEach(tag=>{const b=document.createElement("span");b.className="tag-chip";b.textContent=text(tag);tags.appendChild(b);});const footer=document.createElement("div");footer.className="card-footer";const btn=document.createElement("button");btn.type="button";btn.className="card-view-btn";btn.innerHTML=`View ${icon.arrow}`;btn.addEventListener("click",()=>openModal(card));footer.append(document.createElement("span"),btn);content.append(context,title,p,tags,footer);a.append(media,content);return a; }
  function renderCards(){const q=$("#searchInput").value.trim().toLowerCase();state.filtered=state.cards.filter(c=>(state.category==="All"||text(c.category)===state.category)&&(!q||[c.title,c.game,c.description,c.category,c.version,...(Array.isArray(c.tags)?c.tags:[])].join(" ").toLowerCase().includes(q)));const wrap=$("#cards");wrap.replaceChildren();state.filtered.forEach((c,i)=>wrap.appendChild(cardElement(c,i)));$("#resultCount").textContent=`${state.filtered.length} result${state.filtered.length===1?"":"s"}`;$("#emptyState").classList.toggle("hidden",state.filtered.length!==0);attachTilt(wrap);}
  function openModal(card){const modal=$("#modal");modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.classList.add("modal-open");const media=$("#modalMedia");media.replaceChildren();const img=document.createElement("img");img.src=safeImage(card.image);img.alt=text(card.title);media.appendChild(img);$("#modalGame").textContent=text(card.game||"").toUpperCase();$("#modalTitle").textContent=text(card.title);$("#modalDescription").textContent=text(card.description);$("#modalBadges").replaceChildren();[card.category,card.version,card.status].filter(Boolean).forEach(v=>{const b=document.createElement("span");b.className="tag-chip";b.textContent=text(v);$("#modalBadges").appendChild(b);});$("#modalTags").replaceChildren();(Array.isArray(card.tags)?card.tags:[]).forEach(v=>{const b=document.createElement("span");b.className="tag-chip";b.textContent=text(v);$("#modalTags").appendChild(b);});const url=safeExternal(card.redirect);const get=$("#modalGet");get.href=url||"#";get.setAttribute("aria-disabled",String(!url));const panel=$(".modal-panel");panel.style.setProperty("--accent",card.accent||"#6d7cff");panel.style.setProperty("--accent-end",card.accentEnd||gradients[card.gradient]?.[1]||"#9a5eff");$("#modalCopy").onclick=async()=>{if(!url)return toast("No valid HTTPS link.");try{await navigator.clipboard.writeText(url);toast("Link copied.")}catch{toast("Clipboard permission was blocked.")}};$("#modalCustomize").href=`admin.html?card=${encodeURIComponent(card.id)}`;}
  function closeModal(){$("#modal").classList.remove("open");$("#modal").setAttribute("aria-hidden","true");document.body.classList.remove("modal-open");}
  async function copy(value,msg){try{await navigator.clipboard.writeText(value);toast(msg)}catch{toast("Clipboard permission was blocked.")}}
  function startTyping(){const el=$("#typingStatus");if(!el)return;const n=state.cards.length,c=new Set(state.cards.map(x=>text(x.category)).filter(Boolean)).size,latest=state.cards[0]?.title;const phrases=[n?`${n} script${n===1?"":"s"} in the hub.`:"The hub is warming up.",c?`${c} categor${c===1?"y":"ies"} to explore.`:"Creator drops are landing.",latest?`Latest drop: ${latest}.`:"Fresh creator drops are landing.","Browse. Discover. Drop.","Built for script creators."];let pi=0,pos=0,del=false;const tick=()=>{const ph=phrases[pi%phrases.length];if(!del){pos++;el.textContent=ph.slice(0,pos);if(pos>=ph.length){del=true;setTimeout(tick,1500);return}}else{pos--;el.textContent=ph.slice(0,pos);if(pos<=0){del=false;pi++;setTimeout(tick,220);return}}setTimeout(tick,del?26:44)};el.textContent="";tick();}
  async function load(){const year=$("#year");if(year)year.textContent=new Date().getFullYear();attachTilt(document);try{const r=await api("/api/catalog");const j=await r.json();if(!r.ok)throw new Error(j.error||"Catalog unavailable");state.cards=Array.isArray(j.cards)?j.cards:[];state.cards.sort((a,b)=>Number(Boolean(b.featured))-Number(Boolean(a.featured)));renderFilters();renderCards();$("#scriptCount").textContent=String(state.cards.length);$("#categoryCount").textContent=String(new Set(state.cards.map(c=>text(c.category)).filter(Boolean)).size);const f=state.cards.find(c=>c.featured)||state.cards[0];if(f){$("#featuredCard").style.setProperty("--accent",f.accent||"#6d7cff");$("#featuredCard").style.setProperty("--accent-end",f.accentEnd||gradients[f.gradient]?.[1]||"#9a5eff");$("#featuredImage").src=safeImage(f.image);$("#featuredGame").textContent=text(f.game||"").toUpperCase();$("#featuredCategory").textContent=text(f.category||"").toUpperCase();$("#featuredTitle").textContent=text(f.title||"");$("#featuredDescription").textContent=text(f.description||"");$("#featuredVersion").textContent=text(f.version||"V1.0");$("#featuredButton").onclick=()=>openModal(f);attachTilt($("#featuredCard").parentElement);$("#featuredCard").classList.add("loaded")}}catch(e){toast(e.message||"Catalog unavailable")}startTyping();}
  $("#searchInput").addEventListener("input",renderCards);document.addEventListener("keydown",e=>{if(e.key==="/"&&document.activeElement?.tagName!=="INPUT"&&document.activeElement?.tagName!=="TEXTAREA"){e.preventDefault();$("#searchInput").focus()}if(e.key==="Escape")closeModal()});$$('[data-close]').forEach(el=>el.addEventListener("click",closeModal));$("#copyDiscord")?.addEventListener("click",()=>copy("@vhb7","@vhb7 copied."));load();
})();