(() => {
  const cfg = window.AZU_CONFIG || { API_BASE: "" };
  const API = String(cfg.API_BASE || "").replace(/\/$/, "");
  const state = { cards: [], filtered: [], category: "All" };
  const $ = s => document.querySelector(s);
  const esc = s => String(s ?? "");
  function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),2300)}
  function api(path, options={}){return fetch(API + path, { ...options, headers:{ Accept:"application/json", ...(options.body?{"Content-Type":"application/json"}:{}), ...(options.headers||{}) } })}
  function imgSrc(v){ if(!v)return ""; try{ return new URL(v, location.href).href }catch{return ""} }
  function safeExternal(v){ try{ const u=new URL(v,location.href); return u.protocol==="https:"?u.href:"" }catch{return ""} }
  function attachTilt(root=document){root.querySelectorAll(".tilt-card:not([data-tilt-ready])").forEach(card=>{card.dataset.tiltReady="1";let rect;card.addEventListener("mouseenter",()=>{rect=card.getBoundingClientRect();card.style.transition="none"});card.addEventListener("mousemove",e=>{rect ||= card.getBoundingClientRect();const strength=Number(card.dataset.tiltStrength||6);const x=(e.clientX-rect.left)/rect.width-.5;const y=(e.clientY-rect.top)/rect.height-.5;card.style.transform=`perspective(1000px) rotateX(${(-y*strength).toFixed(2)}deg) rotateY(${(x*strength).toFixed(2)}deg) translateY(-2px)`});card.addEventListener("mouseleave",()=>{card.style.transition="transform .35s ease,box-shadow .25s ease";card.style.transform=""})})}
  function renderFilters(){const categories=["All",...new Set(state.cards.map(c=>c.category).filter(Boolean))];const f=$("#filters");f.replaceChildren();categories.forEach(cat=>{const b=document.createElement("button");b.className="filter"+(cat===state.category?" active":"");b.textContent=cat;b.addEventListener("click",()=>{state.category=cat;renderFilters();renderCards()});f.appendChild(b)})}
  function cardElement(card){const a=document.createElement("article");a.className="script-card tilt-card";a.dataset.tiltStrength="5";const media=document.createElement("div");media.className="card-media";const img=document.createElement("img");img.src=imgSrc(card.image);img.alt=esc(card.title);img.loading="lazy";img.onerror=()=>{img.style.opacity="0"};media.appendChild(img);const shine=document.createElement("div");shine.className="card-shine";media.appendChild(shine);const content=document.createElement("div");content.className="card-content";const top=document.createElement("div");top.className="card-top";const cat=document.createElement("span");cat.className="mini-badge";cat.textContent=esc(card.category||"Other").toUpperCase();const ver=document.createElement("span");ver.className="version";ver.textContent=esc(card.version||"V1");top.append(cat,ver);const h=document.createElement("h3");h.textContent=esc(card.title);const p=document.createElement("p");p.textContent=esc(card.description);const tags=document.createElement("div");tags.className="card-tags";(Array.isArray(card.tags)?card.tags:[]).slice(0,4).forEach(t=>{const s=document.createElement("span");s.className="tag";s.textContent=esc(t);tags.appendChild(s)});const footer=document.createElement("div");footer.className="card-footer";const status=document.createElement("span");status.className="muted";status.textContent=esc(card.status||"Live");const btn=document.createElement("button");btn.className="small-button";btn.textContent="View →";btn.addEventListener("click",()=>openModal(card));footer.append(status,btn);content.append(top,h,p,tags,footer);a.append(media,content);a.style.setProperty("--accent",card.accent||"#6d7cff");return a}
  function renderCards(){const q=$("#searchInput").value.trim().toLowerCase();state.filtered=state.cards.filter(c=>(state.category==="All"||c.category===state.category)&&(!q||JSON.stringify(c).toLowerCase().includes(q)));const wrap=$("#cards");wrap.replaceChildren();state.filtered.forEach(c=>wrap.appendChild(cardElement(c)));$("#resultCount").textContent=`${state.filtered.length} result${state.filtered.length===1?"":"s"}`;$("#emptyState").classList.toggle("hidden",state.filtered.length>0);attachTilt(wrap)}
  function openModal(card){$("#modal").classList.add("open");$("#modal").setAttribute("aria-hidden","false");$("#modalMedia").replaceChildren();const img=document.createElement("img");img.src=imgSrc(card.image);img.alt=esc(card.title);$("#modalMedia").appendChild(img);$("#modalGame").textContent=esc(card.game||"");$("#modalTitle").textContent=esc(card.title);$("#modalDescription").textContent=esc(card.description);$("#modalBadges").replaceChildren();[card.category,card.version].filter(Boolean).forEach(v=>{const s=document.createElement("span");s.className="tag";s.textContent=esc(v);$("#modalBadges").appendChild(s)});$("#modalTags").replaceChildren();(Array.isArray(card.tags)?card.tags:[]).forEach(t=>{const s=document.createElement("span");s.className="tag";s.textContent=esc(t);$("#modalTags").appendChild(s)});const url=safeExternal(card.redirect);const get=$("#modalGet");get.href=url||"#";get.rel="noopener noreferrer";get.target="_blank";get.setAttribute("aria-disabled",!url);$("#modalCopy").onclick=async()=>{if(!url)return toast("No valid HTTPS link.");await navigator.clipboard.writeText(url);toast("Link copied.")};const custom=$("#modalCustomize");custom.href=`admin.html?card=${encodeURIComponent(card.id)}`}
  function closeModal(){$("#modal").classList.remove("open");$("#modal").setAttribute("aria-hidden","true")}
  async function copy(text,msg){try{await navigator.clipboard.writeText(text);toast(msg)}catch{toast("Clipboard permission was blocked.")}}
  async function load(){document.title=cfg.SITE_TITLE||document.title;$("#year").textContent=new Date().getFullYear();try{const r=await api("/api/catalog");const j=await r.json();if(!r.ok)throw new Error(j.error||"Catalog unavailable");state.cards=Array.isArray(j.cards)?j.cards:[];state.cards.sort((a,b)=>(Number(b.featured)||0)-(Number(a.featured)||0));renderFilters();renderCards();$("#scriptCount").textContent=state.cards.length;$("#categoryCount").textContent=new Set(state.cards.map(c=>c.category).filter(Boolean)).size;const f=state.cards[0];if(f){$("#featuredImage").src=imgSrc(f.image);$("#featuredGame").textContent=esc(f.game||"");$("#featuredTitle").textContent=esc(f.title);$("#featuredDescription").textContent=esc(f.description);$("#featuredVersion").textContent=esc(f.version||"");$("#featuredButton").onclick=()=>openModal(f)}}catch(e){toast(e.message||"API error")};attachTilt(document)}
  $("#searchInput").addEventListener("input",renderCards);document.addEventListener("keydown",e=>{if(e.key==="/"&&document.activeElement.tagName!=="INPUT"){e.preventDefault();$("#searchInput").focus()}if(e.key==="Escape")closeModal()});document.querySelectorAll("[data-close]").forEach(x=>x.addEventListener("click",closeModal));$("#copyIp").addEventListener("click",async()=>{try{const r=await api("/api/me/ip");const j=await r.json();if(!r.ok)throw new Error(j.error);await copy(j.ip,"Your IP was copied.");$("#accessStatus").textContent=`Edge sees ${j.ip}`;$("#accessStatus").className="small-status"}catch(e){toast(e.message||"Could not read IP")}});$("#copyHwidCommand").addEventListener("click",()=>copy('powershell -NoProfile -ExecutionPolicy Bypass -File .\\get-hwid.ps1',"HWID helper command copied."));$("#copyApi").addEventListener("click",()=>copy(API||location.origin,"API URL copied."));$("#copyHwid").addEventListener("click",()=>{const v=$("#hwidPaste").value.trim();if(!/^[a-f0-9]{64}$/i.test(v))return toast("Paste a valid 64-character HWID first.");copy(v.toUpperCase(),"HWID copied.")});load();
})();
